### ISSUE TITLE
PyTrilinos for Windows

### ISSUE THREAD

**Issue by wfspotz** [conda-forge/pytrilinos-feedstock#2]
I would like to expand the pytrilinos recipe to include Windows, but I do not have a Windows machine set up for scientific computing to test on. How should I proceed?

**Comment by isuruf** [comment]
You can add a `bld.bat`, remove the skip on windows, rerender and send a PR so that appveyor runs it. You can iterate on appveyor builds. You can even login to appveyor machines using rdp (only for one hour after the job starts though). It'll be better if you setup an appveyor account and set it up for your fork, so that you don't have to wait in the `conda-forge` queue.

**Comment by wfspotz** [comment]
Is `bld.bat` written in DOS? I will need some guidance.

**Comment by isuruf** [comment]
Have a look at symengine-feedstock for a windows CMake example

**Comment by wfspotz** [comment]
OK, I sent a PR, but it does not look like appveyor is running it.

**Comment by wfspotz** [comment]
I am going to close this for now, since openmpi is not supported on Windows.
